CREATE OR REPLACE STAGE PEOPLE_STAGE;

CREATE OR REPLACE TABLE PEOPLE_DB.PEOPLE_SCHEMA.PEOPLE(
    ID INT,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    AGE INT,
    SALARY FLOAT,
    JOINDATE DATE,
    ACTIVE STRING,
    DEPARTMENT STRING,
    EMAIL STRING,
    EXPERIENCE_YEARS INT,
    REMOTE BOOLEAN
);